apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: registry.hub.docker.com/dock15/cicd:v3
        name: guestbook-ui
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: dockersect
